import { DEVICE_CATEGORIES } from "../models/DeviceCategories";

export const DEVICE_CATEGORY_LABELS: {[permission in DEVICE_CATEGORIES]: string} = {
    [DEVICE_CATEGORIES.ROUTER]: "Router",
    [DEVICE_CATEGORIES.ROUTER_WIFI]: "WiFi router",
    [DEVICE_CATEGORIES.PHONE]: "Phone",
    [DEVICE_CATEGORIES.LAPTOP]: "Laptop",
    [DEVICE_CATEGORIES.WORKSTATION]: "Desktop",
    [DEVICE_CATEGORIES.TABLET]: "Tablet",
    [DEVICE_CATEGORIES.TV]: "Tv",
    [DEVICE_CATEGORIES.HUB]: "Hub",
    [DEVICE_CATEGORIES.CAMERA]: "Camera",
    [DEVICE_CATEGORIES.SMART_SPEAKER]: "Speaker",
    [DEVICE_CATEGORIES.UNKNOWN]: "Unknown",
};